/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.finlogic.util;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.springframework.stereotype.Service;




/**
 *
 * @author njuser
 */
@Service
public class JSONUtility {

    
   public JSONObject getJSONObject(List<HashMap<String, String>> data) {

        JSONObject json = new JSONObject();
        json.put("data", data);

        return json;
    }

    public JSONArray getJSONArray(List<HashMap<String, String>> data) {

        JSONArray json = new JSONArray();
        json.add(data);

        return json;
    }

    public JSONObject findByAutoGeneratedID(JSONArray array, String _id) {
        JSONObject object = new JSONObject();

        for (int i = 0; i < array.size(); i++) {
            object = (JSONObject) array.get(i);
            String id = (String) object.get("_id");
            
            if (id.equals(_id)) {
                return object;
            }
        }
        
        return object;
    }

    public Map toMap(JSONObject obj) {
        Map<String, String> map = new HashMap<>();

        System.out.println("Outside");
        obj.forEach(new BiConsumer() {
            @Override
            public void accept(Object k, Object v) {
                map.put((String)k,(String)v);
            }
        });
        
        return map;
    }
    
    public Map getPlaceholderData(Map<String,String> data){
        Map<String,String> map = new HashMap<>();
        for (String key : data.keySet()) {
            String value = data.get(key);
            String placeholdeKey = "{{" + key.replace(" ", "_") +"}}";
            map.put(placeholdeKey, value);
        }
        return map;
    }
    
    public String getJSONString(List data){
        String json = JSONArray.toJSONString(data);
        return json;
    }
    
}
